services:
  server:
    build:
      context: server/proyecto-fin-de-grado
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - database
    healthcheck:
      test: curl --fail http://localhost:8081/health || exit 1
      interval: 40s
      timeout: 180s
      retries: 3
      start_period: 100s
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/mhcdatabase
    volumes:
      - ./server/proyecto-fin-de-grado:/app
    command: "mvn spring-boot:run"

  client:
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      server:
        condition: service_healthy
    volumes:
      - ./client:/app
      - /app/node_modules
    command: "npm run dev -- --host"

  database:
    container_name: mhc_db
    image: mysql:latest
    ports:
      - "3300:3306"
    environment:
      MYSQL_DATABASE: mhcdatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      TZ: Europe/Madrid
    volumes:
      - database:/var/lib/mysql

volumes:
  database:


