server.port=8081

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/mhcdatabase
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

spring.security.oauth2.client.registration.google.client-id=1010005389878-61irtvrjifovlcs4r7mrej4k9jeh07op.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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

jwt.secret=7c52b395da431e6a371957f620305891b9bab30c37f856e9af2871faa58f325d

spring.ai.ollama.base-url=http://host.docker.internal:11434
spring.ai.ollama.chat.options.model=llama3.1